travis:
  secure:
    BINSTAR_TOKEN: fQjN8vVbuZs+s2hA/cdy6rUPrzRTIsYSUtkY4t9hBAVFno1UD9+E2XYU/AzFy658S014x8GgUnlCZsBm0BVBHd0I038IQVH3YPR+2UANc6giPyj7urWgpGk6lCXv96wrVHxlMMKeZEsEbSjahxRdn0OR0KRuIEIK/Vlzct+7Or9EhJzePIRgLfPDNUlY6DZwyl/k8ANAou1ku/TO2WubaxNO6cHQAjlNf6Q7kvBIILIuVbzCblQZPEnVqIaWbqZErt8G2sSZlFQc3iDP8QTXqBBubpCni6Cpb6K1j/j/seuGsosiP8XmVWV/mqzwIZPlsr9blFCUjVBZr7oIMXTo98bmMx4Mq4UcaP6IGeVOMKLTcbqG0LNJghY5KWDXfw8uXg9kQW0C1CroM9spYfjKQ9H4v8ZCpzuoEsAZIQvhAUAsknk/squYJ7g/OZUsvDJf0KsYkQjA1ymeA3JS2cVqdSkcdXwuVGy+bWr9pT9D07UszM1lKOxGMaMB3Doql3MAv5ntJYZSDON97e+4X/I6GjUSG3xCjDTTGSWBm2jj87ATqRsFa5EUKkZ0+nFC23HgkGFNmXA4DzeOJFIv+Q12ozETNzb5nnuzxaFS/C9Upup3TrJ0m6uR2YGJmVhrGDDCZFgHdMa2D6ueQp98fYbydhmsVkFkv9i3Y7VZkuBgK7g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
